/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import Fonksiyonlar.aliciDao;
import Fonksiyonlar.ilceDao;
import Fonksiyonlar.kargoDao;
import Fonksiyonlar.kullaniciDao;
import dto.alici;
import dto.tablolar;
import dto.ilceler;
import java.awt.HeadlessException;
import java.sql.Date;
import java.util.Random;
import javax.swing.JOptionPane;

public class Kargo_Gonder extends javax.swing.JFrame {

    public static String takipNo;
    public static String urunTanimi;
    public static double agirlik;
    public static int kirilabilir;
    public static String ad;
    public static String soyad;
    public static String aliciAdres;
    public static String telefon;
    public static String il;
    public static String ilce;
    public static Date gondermeTarihi;
    public static int kullanici_lat;
    public static int kullanici_lon;
    static alici alici1;
    public static int alici_lat;
    public static int alici_lon;
    public static int ucret;
    public static int kapidaOdeme = 1;

    private static String loggedInUsername;
    
    public Kargo_Gonder(String loggedInUsername) {
        initComponents();
        Kargo_Gonder.loggedInUsername = loggedInUsername;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rd_kirilabilir = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txt_urunTanimi = new javax.swing.JTextField();
        txt_agirlik = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rd_kapidaOdeme = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmb_il = new javax.swing.JComboBox();
        cmb_ilce = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_firstName = new javax.swing.JTextField();
        txt_lastName = new javax.swing.JTextField();
        txt_Address = new javax.swing.JTextField();
        txt_telNo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_gonder = new javax.swing.JButton();
        lbl_tutar = new javax.swing.JLabel();
        btn_Back = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Ürün Tanımı:");

        jLabel5.setText("Ağırlık (KG): ");

        rd_kirilabilir.setText("Kırılabilir");

        jLabel6.setText("Kargo Tipi: ");

        txt_agirlik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_agirlikActionPerformed(evt);
            }
        });
        txt_agirlik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_agirlikKeyPressed(evt);
            }
        });

        jLabel8.setText("Ödeme Tipi:");

        rd_kapidaOdeme.setText("Kapıda Ödeme");
        rd_kapidaOdeme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_kapidaOdemeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Kargo Bilgileri");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_agirlik, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rd_kirilabilir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rd_kapidaOdeme)
                            .addComponent(txt_urunTanimi, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel11)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_urunTanimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_agirlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rd_kirilabilir))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rd_kapidaOdeme))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 220));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Alıcı Adresi: ");

        cmb_il.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bir il seçiniz", "ADANA", "ADIYAMAN", "AFYON", "AĞRI", "AKSARAY", "AMASYA", "ANKARA", "ANTALYA", "ARDAHAN", "ARTVİN", "AYDIN", "BALIKESİR", "BARTIN", "BATMAN", "BAYBURT", "BİLECİK", "BİNGÖL", "BİTLİS", "BOLU", "BURDUR", "BURSA", "ÇANAKKALE", "ÇANKIRI", "ÇORUM", "DENİZLİ", "DİYARBAKIR", "DÜZCE", "EDİRNE", "ELAZIĞ", "ERZİNCAN", "ERZURUM", "ESKİŞEHİR", "GAZİANTEP", "GİRESUN", "GÜMÜŞHANE", "HAKKARİ", "HATAY", "IĞDIR", "ISPARTA", "İSTANBUL", "İZMİR", "KAHRAMANMARAŞ", "KARABÜK", "KARAMAN", "KARS", "KASTAMONU", "KAYSERİ", "KİLİS", "KIRIKKALE", "KIRKLARELİ", "KIRŞEHİR", "KOCAELİ", "KONYA", "KÜTAHYA", "MALATYA", "MANİSA", "MARDIN", "MERSİN", "MUĞLA", "MUŞ", "NEVŞEHİR", "NİĞDE", "ORDU", "OSMANİYE", "RİZE", "SAKARYA", "SAMSUN", "ŞANLIURFA", "SİİRT", "SİNOP", "SİVAS", "ŞIRNAK", "TEKİRDAĞ", "TOKAT", "TRABZON", "TUNCELİ", "UŞAK", "VAN", "YALOVA", "YOZGAT", "ZONGULDAK" }));
        cmb_il.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ilActionPerformed(evt);
            }
        });

        cmb_ilce.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bir ilçe seçiniz", " " }));
        cmb_ilce.setMinimumSize(new java.awt.Dimension(116, 22));
        cmb_ilce.setPreferredSize(new java.awt.Dimension(116, 22));
        cmb_ilce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ilceActionPerformed(evt);
            }
        });

        jLabel3.setText("Ad:");

        jLabel4.setText("Soyad: ");

        jLabel7.setText("Telefon: ");

        txt_telNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telNoActionPerformed(evt);
            }
        });
        txt_telNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telNoKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Alıcı Bilgileri");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(cmb_il, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_ilce, 0, 1, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_telNo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(txt_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_firstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_lastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_il, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_ilce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 340, 220));

        btn_gonder.setText("Gönder");
        btn_gonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gonderActionPerformed(evt);
            }
        });
        jPanel3.add(btn_gonder, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, 30));

        lbl_tutar.setText("Tutar:");
        jPanel3.add(lbl_tutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 73, -1));

        btn_Back.setText("<");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 68, 33));

        jLabel9.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel9.setText("Kargo Gönder");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 230, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_ilceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ilceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_ilceActionPerformed

    private void cmb_ilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ilActionPerformed
        String secili_il = cmb_il.getSelectedItem() + "";
        agirlik = 0;
        if (!(txt_agirlik.getText().equals(""))) {
            agirlik = Double.parseDouble(txt_agirlik.getText());
        }
        
        cmb_ilce.removeAllItems();
        for (ilceler i : ilceDao.ilceGoster(secili_il)) {
            cmb_ilce.addItem(i.getIsim());
        }
        // System.out.println(Login.online.getIl());
        for (tablolar b : kullaniciDao.Kullanici_koordinatlari()) {
            kullanici_lat = b.getLat();
            kullanici_lon = b.getLon();
            b = null;
        }

        for (tablolar c : aliciDao.alici_koordinatlari(secili_il)) {
            alici_lat = c.getLat();
            alici_lon = c.getLon();
            c = null;
        }
        //System.out.println("secili il     ." + secili_il + ".s");
        //System.out.println("lat :" + alici_lat + "  lon : " + alici_lon);
        double distance = kargoDao.getdistance(kullanici_lat, kullanici_lon, alici_lat, alici_lon);

        double price = kargoDao.getCargoPrice(distance, agirlik);

        ucret = (int) price;
        lbl_tutar.setText(ucret + " TL");


    }//GEN-LAST:event_cmb_ilActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        this.setVisible(false);  // register ekranını kapatıyoruz
        new Kullanici_Paneli(loggedInUsername).setVisible(true);// login ekranını tekrar açıyoruz.
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_gonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gonderActionPerformed

        Date date = new Date(System.currentTimeMillis());
        gondermeTarihi = date;

        boolean exists = true;
        while (exists) {
            Random sayi = new Random(); //random sınıfı
            takipNo = "C" + sayi.nextInt(1000000) + "";
            exists = kargoDao.takip_no_isexist(takipNo);
        }

        urunTanimi = txt_urunTanimi.getText();
        ad = txt_firstName.getText();
        soyad = txt_lastName.getText();
        telefon = txt_telNo.getText();
        il = cmb_il.getSelectedItem() + "";
        ilce = cmb_ilce.getSelectedItem() + "";
        aliciAdres = txt_Address.getText() + " " + ilce + " - " + il;
        kirilabilir = 0;

        if (rd_kirilabilir.isSelected()) {
            kirilabilir = 1;
        }

        if (rd_kapidaOdeme.isSelected()) {
            kapidaOdeme = 2;
        } else {
            kapidaOdeme = 1;
        }

        if (gondermeTarihi.equals("") || urunTanimi.equals("") || ad.equals("") || soyad.equals("") || telefon.equals("") || il.equals("Bir il seçiniz") || aliciAdres.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Boş alanları doldurunuz!");
        } else {

            try {
                aliciDao.addAlici(ad, soyad, telefon, ilce, il, aliciAdres);
                alici1 = aliciDao.aliciBilgileri(telefon, ad, soyad).get(0);
                System.out.println(takipNo);
                kargoDao.sendKargo(takipNo, agirlik, kirilabilir, aliciAdres, Login.online.getKullaniciId(), alici1.getAlici_Id(), urunTanimi, gondermeTarihi, 1, ucret, kapidaOdeme);
                JOptionPane.showMessageDialog(null, "İşlem başarılı!");

                txt_urunTanimi.setText("");
                txt_agirlik.setText("");
                txt_firstName.setText("");
                txt_lastName.setText("");
                txt_telNo.setText("");
                txt_Address.setText("");
                rd_kirilabilir.setSelected(false);
                lbl_tutar.setText("");
                JOptionPane.showMessageDialog(rootPane, "Kargo Takip Numaranız: " + takipNo);

            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Bir hata meydana geldi!");
                System.out.println(e);

            }
        }

    }//GEN-LAST:event_btn_gonderActionPerformed

    private void txt_telNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telNoKeyPressed

        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == 8) {
            txt_telNo.setEditable(true);

        } else {
            txt_telNo.setEditable(false);
            JOptionPane.showMessageDialog(rootPane, "*Bu alana sadece rakam girebilirsiniz!");

        }
    }//GEN-LAST:event_txt_telNoKeyPressed

    private void txt_telNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telNoActionPerformed

    private void rd_kapidaOdemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_kapidaOdemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_kapidaOdemeActionPerformed

    private void txt_agirlikKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_agirlikKeyPressed

        String value = txt_agirlik.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == 8) {
            txt_agirlik.setEditable(true);

        } else {
            txt_agirlik.setEditable(false);

            JOptionPane.showMessageDialog(rootPane, "*Bu alana sadece rakam girebilirsiniz!");
        }
    }//GEN-LAST:event_txt_agirlikKeyPressed

    private void txt_agirlikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_agirlikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_agirlikActionPerformed

    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Kargo_Gonder(loggedInUsername).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_gonder;
    private javax.swing.JComboBox cmb_il;
    private javax.swing.JComboBox cmb_ilce;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_tutar;
    private javax.swing.JRadioButton rd_kapidaOdeme;
    private javax.swing.JRadioButton rd_kirilabilir;
    private javax.swing.JTextField txt_Address;
    private javax.swing.JTextField txt_agirlik;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_telNo;
    private javax.swing.JTextField txt_urunTanimi;
    // End of variables declaration//GEN-END:variables
}
